name: PhantomCombat
main: io.github.lokka30.phantomcombat.PhantomCombat
version: ${project.version}
api-version: '1.15'
author: lokka30

description: Enhance your combat experience!
website: https://www.spigotmc.org/resources/%E2%9A%94-phantomcombat-%E2%9A%94-enhance-your-combat-experience.74060/

commands:
  phantomcombat:
    description: View some plugin information.
    aliases: [combat]
  stats:
    aliases: [pvpstats, stat, kills, deaths, kdr]
    description: View a targets PvP stats.
  deathcoords:
    aliases: [deathcoordinates, deathcoord, deathlocation, deathloc]
    description: View the location of your last death.
  graceperiod:
    description: Manage a targets grace period.

permissions:
  phantomcombat.*:
    default: op
    description: all permissions
    children:
      phantomcombat.grace-period: true
  phantomcombat.grace-period:
    description: manage grace period
    default: op