#Welcome to the PhantomCombat settings configuration!
#
#Is this file not loading properly? Put the file through a Yaml Parser!
# Popular link: https://yaml-online-parser.appspot.com/
#
#For support, please open a private message to lokka30.
# Attempting to get support in reviews may revoke my assistance.

#It might be frustrating when your enemy logs out whilst in battle. Combat mode solves that.
combat-mode:
  enable: true

  #What worlds should combat mode take effect? Case sensitive.
  enabled-worlds:
    - 'world'
    - 'world_nether'
    - 'world_the_end'

  #What gamemodes should combat mode take effect? Must be in uppercase.
  enabled-gamemodes:
    - SURVIVAL
    - ADVENTURE

  #What combat causes should engage the defender in combat?
  enabled-combat-causes:
    #player: attacker is a player.
    player: true

    #entity: attacker is an entity, but not a player.
    entity: true

    #generic: damage was from a generic cause, e.g. contact with a cactus, fall damage...
    generic: false

  #Time until combat mode expires, in seconds.
  time: 15

  effects:
    #Effects of when a user leaves whilst in combat mode.
    combat-log:
      kill-player: true
      lightning-strike-effect: true
      broadcast-location: false

    #Sounds on combat started
    combat-started:
      enable: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1.0
      pitch: 0.0

    #Sounds on combat finished
    combat-finished:
      enable: true
      sound: ENTITY_PLAYER_LEVELUP
      volume: 1.0
      pitch: 2.0

  block-flight: false

  #Block all teleports (including plugin-caused)?
  block-teleport: false

  #List of items to cancel interact with in hands in combat mode. Must be in uppercase.
  block-items:
    enable: true
    items:
      - ENDER_PEARL
      - CHORUS_FRUIT

  #Block commands from being processed in combat mode.
  block-commands:
    enable: true

    #commands must contain a starting slash
    commands:
      - /tpa
      - /tpaccept
      - /tpdeny
      - /spawn
      - /home
      - /warp
      - /tp
      - /tphere
      - /fly

death-coords:
  enable: true

blood:
  enable: true

  #What worlds should bleeding take effect?
  enabled-worlds:
    - world
    - world_nether
    - world_the_end

  #Should entities bleed (not players)?
  entities-bleed: true

  #Should players bleed?
  players-bleed: true

  #Want to toggle specific causes?
  cause:
    fall: true
    drowning: false
    starvation: false
    suffocation: false
    contact: true
    fire: false

armor-hit-sound:
  enable: true
  sound: 'ENTITY_ZOMBIE_ATTACK_IRON_DOOR'
  volume: 0.7
  pitch: 1.8

grace-period:
  enable: true

  #Time until expiry (seconds)
  time: 300

  #Should PhantomCombat check for a players' grace period
  #after a scheduler, or when they next engage in combat?
  #Defaults to true for convenience, however, setting it to
  #false will yield better performance.
  scheduler: true

  #In what ways can the grace period messages be communicated?
  communication:
    chat: true
    action-bar: false

pvp-settings:
  #Should the 1.9 Combat Update hit delay be removed?
  no-hit-delay: false

pvp-toggle:
  #Should the PvP-Toggle module be enabled?
  enable: true

#Check for updates?
updater: true

#I recommend you leave this number as it is.
# If you've updated your configuration with
# values from the new update, you may change it.
# DO NOT leave this empty, your settings will be reset!
file-version: 6